version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
    ports:
      - "2379:2379"
      - "2380:2380"
    command: /usr/local/bin/etcd --name spring-integration-etcd-test --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 --debug